### PR TITLE
Simplify updating license year on modified files

### PR DESCRIPTION
**Pull request by elefeint**
New script that checks all added/modified/created files and updates license end year to the current year.

### CODE REVIEW

**Comment by elefeint** [comment]
I'll make it not run automatically and instead be an invokable maven target -- @meltsufin pointed out that `bash` presence cannot be assumed.

**Comment by meltsufin** [comment]
Separate from automatic fix (that can be run manually), I think we should just have a check that detects when the copyright header has the wrong date. The check can just run automatically on Travis build.

**Comment by elefeint** [comment]
I removed the maven changes entirely. The script is useful, but can be run from command line just as well; does not need to be a maven target if it's not going to be run automatically.
Tested it on #1372, seems to work.

**Comment by meltsufin** [comment]
@elefeint I still see changes in `pom.xml`.

**Comment by meltsufin** [comment]
@elefeint Maybe drop a line about it in https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc?

**Pull request merged**
