### PR TITLE
Adds .travis.yml file

### PR DESCRIPTION
**Pull request by joaoandremartins**
Makes Travis build Java instead of Ruby.

Helps with #21

### CODE REVIEW

**Comment by artembilan** [comment]
In the Gradle projects we have:
```
script:
    - ./gradlew check --refresh-dependencies --no-daemon
```
How does this "empty" config understand that it must call `./mvnw package` ?

Thanks

**Comment by joaoandremartins** [comment]
It's calling `./mvnw test` by default. And it also calls `install` before to install dependencies.

https://docs.travis-ci.com/user/languages/java/#Default-script-Command

Do we want it to do anything differently?

**Comment by meltsufin** [comment]
On other projects we do something like this, but I think the default is fine for now.

```yaml
script:
  # execute regular local build
  - mvn clean verify -B -V -q
```

**Comment by artembilan** [comment]
Why did you merge this?
I didn't approve.

I really would like to see Checkstyle results in the Travis as well.

Thanks

**Comment by joaoandremartins** [comment]
Sorry @artembilan I thought we could get any changes merged to `.travis.yml` as we needed them.

`./mvn test` runs checkstyle, it will fail if there are any issues.

**Comment by artembilan** [comment]
Yeah... Confirmed:
```
D:\SpringIO\spring-cloud\spring-cloud-gcp>mvnw test
[INFO] Scanning for projects...
...
[ERROR] src\main\java\org\springframework\cloud\gcp\pubsub\support\SubscriberFactory.java:[29,54] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
```

I was under impression that we couldn't manage to work Checkstyle in some other project only via just `test` goal. We have to run `package` there...

Cool! Thank your for the patience! And sorry for extra noise.

**Pull request merged**
