### PR TITLE
Moved Spring Cloud Config README from Autoconfigure to the Config Starter

### PR DESCRIPTION
**Pull request by saturnism**
For #397.

Spring Cloud GCP Config sample also references to this file.

### CODE REVIEW

**Comment by joaoandremartins** [comment]
I think @artembilan is of the opinion that Spring users aren't used to looking for documentation in the starters, since they're only a collection of dependencies.
However, since we have READMEs in other starters, it might make sense to have the Config one there too.
Would you guys be opposed to gathering all of the READMEs in a single one, in the `autoconfigure` module?

**Comment by meltsufin** [comment]
+1 for not duplicating docs.

Regarding this PR, however, config is the only starter for which the README was moved into autoconfigure. I think for the consistency with other starters, it should move back as this PR proposes.

Ultimately, we might want to move all starter docs into a single README or the refdoc, but that's a separate conversation.

**Comment by artembilan** [comment]
Well, for consistency we don't have to have READMEs in starters at all. 

And if we have such a conversion already now why should we push it into the future, but don't just fix as a part of this PR? You definitely do logical things, but the final picture doesn't look like a set of reasonable actions. I mean what is the point to do this task if we agreed to redo it in the future?

I always tried to keep you away from these READMEs, but looks like I don't have enough authority in conviction... If we wouldn't have them in the beginning, there wouldn't be this discussion and such a PR at all.

**Comment by saturnism** [comment]
It's currently linked from another place.

It would make sense if all READMEs are removed from starters and folded into ref doc one way or another. Should that be the next step?

**Pull request merged**
