### PR TITLE
Doc Pom plugins update

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
removed old docs pom plugins for docbook. using new ones in common with other Spring cloud projects.

### CODE REVIEW

**Comment by artembilan** [comment]
Have you build the docs after this your change?
How does it look?

Thanks

**Comment by ChengyuanZhao** [comment]
Looks like the correct pages are being generated:

image

image

**Comment by artembilan** [comment]
@ryanjbaxter,

Is this expected behavior ?

Thanks

**Comment by ryanjbaxter** [comment]
That looks right.

@ChengyuanZhao is there also a generated-docs folder with the html (and xml) in it?

**Comment by ChengyuanZhao** [comment]
@ryanjbaxter yup here it is  

image

**Comment by ryanjbaxter** [comment]
LGTM!

**Pull request merged**
