### PR TITLE
Data store health

### PR DESCRIPTION
**Pull request by nsrags**
[com.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/2829104/com.zip)

### CODE REVIEW

**Comment by meltsufin** [comment]
It looks like you need to rebase on the latest master.

**Comment by ChengyuanZhao** [comment]
@nsrags Could you apply the source code changes in your zip file to this pull request so we can review them?

**Comment by nsrags** [comment]
@meltsufin ,@ChengyuanZhao 
Sorry for confusion . We will create proper pull request .
These changes are related Data store check ( Spring Boot Actuator). Should i commit changes in  spring-cloud-gcp or  Spring boot Actuator GIT( https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-actuator ) ?  Please confirm.

**Comment by meltsufin** [comment]
@nsrags I think it's fine to put the changes in this repo. Thanks!

**Comment by nsrags** [comment]
I have created a different branch and pull request for these changes. Please review
https://github.com/spring-cloud/spring-cloud-gcp/pull/1457

**Pull request closed without merging**
