### PR TITLE
Add Linkage Checker Enforcer Rules

### PR DESCRIPTION
**Pull request by meltsufin**
See: https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/enforcer-rules

### CODE REVIEW

**Comment by meltsufin** [comment]
This plugin needs more memory than the default to run. So, one must first run this command:
```
$ export MAVEN_OPTS='-Xmx2g'
$ mvn clean install -DskipTests
```

**Comment by meltsufin** [comment]
See: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/589
See: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/592

**Comment by meltsufin** [comment]
@suztomo Does this look right to you? Should we be running the enforcer only on the BOM that we provide?

Also, I'm getting these warnings:
```
[WARNING] Could not validate integrity of download from http://www.terracotta.org/download/reflector/releases/org/slf4j/slf4j-api/maven-metadata.xml: Checksum validation failed, expected a19ee04115622963d6ca3efb5509550b9c097e5e but is 52fec9d8dfd13ef3f5e592604e6e3e6d7d19a9f3
```
Is this normal?

Finally, it seems to run for a very long time. (Still waiting for the first run to finish as I write this.)

**Comment by suztomo** [comment]
Strange the build was terminated at maven-install-plugin:

```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ spring-cloud-gcp-pubsub-stream-binder-functional-sample-test ---
[INFO] Installing /home/travis/build/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/target/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test-1.2.3.BUILD-SNAPSHOT.jar to /home/travis/.m2/repository/org/springframework/cloud/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/1.2.3.BUILD-SNAPSHOT/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test-1.2.3.BUILD-SNAPSHOT.jar
[INFO] Installing /home/travis/build/spring-cloud/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/pom.xml to /home/travis/.m2/repository/org/springframework/cloud/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test/1.2.3.BUILD-SNAPSHOT/spring-cloud-gcp-pubsub-stream-binder-functional-sample-test-1.2.3.BUILD-SNAPSHOT.pom
[WARNING] Could not validate integrity of download from http://www.terracotta.org/download/reflector/releases/org/slf4j/slf4j-api/maven-metadata.xml: Checksum validation failed, expected a19ee04115622963d6ca3efb5509550b9c097e5e but is 52fec9d8dfd13ef3f5e592604e6e3e6d7d19a9f3
[WARNING] Could not validate integrity of download from https://repo1.maven.org/maven2/org/slf4j/slf4j-jcl/1.0.1/slf4j-jcl-1.0.1.pom: Checksum validation failed, expected 7035ae7774a9a082a316a6943bbad9dfab6319b3 but is c5c0a3fff6071a4c720f1b7aa1b66cb9d0b26a21
[WARNING] Could not validate integrity of download from https://repo1.maven.org/maven2/org/opensaml/opensaml/maven-metadata.xml: Checksum validation failed, expected b50e385d27683179ca2de5043f96c1252301aca5 but is 7576ac94d82160710ee133d885e0ce71339e0ef1
[WARNING] Could not validate integrity of download from https://repo.maven.apache.org/maven2/org/opensaml/opensaml/maven-metadata.xml: Checksum validation failed, expected b50e385d27683179ca2de5043f96c1252301aca5 but is 7576ac94d82160710ee133d885e0ce71339e0ef1
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

https://travis-ci.org/github/spring-cloud/spring-cloud-gcp/builds/689315888

**Comment by suztomo** [comment]
I get timeout from spring repository. I'll try tomorrow.


```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:50 min
[INFO] Finished at: 2020-05-20T20:11:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.5.BUILD-SNAPSHOT:repackage (repackage) on project spring-cloud-gcp-integration-pubsub-sample-test: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.2.5.BUILD-SNAPSHOT:repackage failed: Plugin org.springframework.boot:spring-boot-maven-plugin:2.2.5.BUILD-SNAPSHOT or one of its dependencies could not be resolved: Failed to collect dependencies at org.springframework.boot:spring-boot-maven-plugin:jar:2.2.5.BUILD-20200227.120635-66 -> org.springframework.boot:spring-boot-loader-tools:jar:2.2.5.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.springframework.boot:spring-boot-loader-tools:jar:2.2.5.BUILD-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-loader-tools:pom:2.2.5.BUILD-SNAPSHOT from/to spring-snapshots (https://repo.spring.io/snapshot): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out (Connection timed out) -> [Help 1]

```

**Comment by suztomo** [comment]
>  Should we be running the enforcer only on the BOM that we provide?

That is a nice idea to reduce build time. (But still high possibility that it gets stuck somewhere in the dependency graph)

**Comment by suztomo** [comment]
I'm afraid that I don't have quick answer for the slowness. I created an issue to followup:
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1418

**Comment by meltsufin** [comment]
Superseded by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/56

**Pull request closed without merging**
