### PR TITLE
Updates to 1.1.0.M2

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by meltsufin** [comment]
@spencergibb FYI

**Comment by spencergibb** [comment]
:+1:

**Comment by artembilan** [comment]
@meltsufin ,

I believe now we need to merge the second commit from @spencergibb , otherwise we fail on CI during pushing `1.1.0.M2` artifact: https://jenkins.spring.io/blue/organizations/jenkins/spring-cloud-gcp-master-ci/detail/spring-cloud-gcp-master-ci/437/pipeline

**Comment by meltsufin** [comment]
Here it is: https://github.com/spring-cloud/spring-cloud-gcp/pull/1045

**Pull request merged**
