### PR TITLE
Updates to boot 2.3 and back to 2.x build

### PR DESCRIPTION
**Pull request by spencergibb**

### CODE REVIEW

**Comment by elefeint** [comment]
The checkstyle version enforcement was in the samples root project, so that checkstyle project can run their snapshot regression tests against `spring-cloud-gcp`. Is it causing issues?

**Comment by spencergibb** [comment]
Yeah, first there's a check for snapshots, now I'm getting a weird compile error in samples. I think it has to do with the mismatched boot version.

**Comment by spencergibb** [comment]
Can't rely on 3.x stuff since it's not released

**Comment by elefeint** [comment]
Build fails with `Failed during checkstyle execution: Unable to find configuration file at location: checkstyle.xml: Could not find resource 'checkstyle.xml'`.

I recall that checkstyle moved somewhere else in the last couple of months in spring cloud build; perhaps we need to provide a customized location? 

Note that the samples do not inherit from `spring-cloud-gcp`, and instead inherit from `spring-boot-starter-parent`. That's why `spring-cloud-build-tools` was needed as a checkstyle dependency in samples pom.

**Comment by spencergibb** [comment]
Ah, then they need to be restored to the 2.3.x branch of spring cloud build

**Comment by dzou** [comment]
@spencergibb - Do you still need these changes? Or are they no longer necessary after the release?

**Comment by spencergibb** [comment]
I think they were taken care of elsewhere

**Pull request closed without merging**
