### PR TITLE
Spanner option to exclude interleaved properties from mapping

### LINKED ISSUE #1133: Spanner change includeColumns param to includeProperties to also apply to interleaved properties

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
fixes #1133 

Allow users to set option to exclude mapping interleaved properties

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@meltsufin We don't have this this specifically listed in the refdoc, and that's intentional because it is in the SpannerReadOptions and SpannerQueryOptions objects with obvious getters and setters. The ref doc is getting pretty big and cluttered, and I didn't think this was a big structural feature (like relationships and transactions) to deserve a mention there. In any case, I think a user would quickly discover it if they needed it.

**Comment by meltsufin** [comment]
@ChengyuanZhao What about my comment regarding exclude vs. include properties?

**Comment by ChengyuanZhao** [comment]
@meltsufin I thought about it from the perspective of using one POJO for multiple different queries (as we have seen from some customers). In that scenario I think it's easier for a user to think in terms of what he or she  DOES need rather than what we DOESN'T need in each case.

**Comment by meltsufin** [comment]
It seems like it would be difficult to use for someone who just wants to store all properties, which I imagine would be a common case.

**Comment by ChengyuanZhao** [comment]
@meltsufin if the Set is null then of course we include everything.

**Comment by meltsufin** [comment]
I see. That works I guess. It's a bit unusual that a null set is equivalent to the full set, rather than the empty set, but OK.

**Pull request merged**
