### PR TITLE
updating correct DocumentId package

### PR DESCRIPTION
**Pull request by jmorla**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jmorla Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2131)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2131) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by meltsufin** [comment]
@jmorla thanks for the contribution.
Please sign the Pivotal CLA before we can accept your PR.

**Comment by jmorla** [comment]
Sorry for the delay I already did the synchronization

**Comment by meltsufin** [comment]
@artembilan Why is the cla check still not passing?

**Comment by artembilan** [comment]
> Why is the cla check still not passing?

Because it looks like @jmorla has not signed it yet.

We can merge this though as an "Obvious Fix" without requiring signing the CLA.

It can be bypassed with this: 

> If your contribution is an Obvious Fix, please mention the CLA bot in a comment or the PR body message like this: “@pivotal-issuemaster This is an Obvious Fix”. 

See https://cla.pivotal.io/about

**Comment by pivotal-issuemaster** [comment]
@jmorla This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by elefeint** [comment]
I need a whole new identity with ObviousFix as the handle now.

**Pull request merged**
