### PR TITLE
Fix Travis "tar: write error" [WIP]

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by meltsufin** [comment]
https://github.com/travis-ci/travis-ci/issues/10169

**Comment by meltsufin** [comment]
The problem went away magically.

**Comment by srfrnk** [comment]
Anyone know how to get that magic for my build?
https://travis-ci.org/DAVFoundation/ride-hailing-api/builds/442049115

**Comment by srfrnk** [comment]
> Anyone know how to get that magic for my build?
> https://travis-ci.org/DAVFoundation/ride-hailing-api/builds/442049115

So if anyone sees this the magic is using this instead (added `>/dev/null`):
```bash
curl https://sdk.cloud.google.com | bash >/dev/null
```

**Comment by williamli** [comment]
@srfrnk nice. thanks. so just disable those excessive logging

**Pull request closed without merging**
