### PR TITLE
fixes #2404 by upgrading error prone to 2.4.0

### LINKED ISSUE #2404: Upgrade to Error Prone 2.4.0 and enable it for JDK 14 builds
See: https://github.com/google/error-prone/releases/tag/v2.4.0

Undo: #2372.

### PR DESCRIPTION
**Pull request by mac2000**
hopefully will fix the issue with error-prone, got the same issue but with a different class, did try to switch between 8, 11, 15 but the error still persists, after upgrading error-prone at least got further

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mac2000 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2624)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2624) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mac2000 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2624)!

**Comment by mac2000** [comment]
heh, and it did not

in idea with java 15, everything seems to be fine but in CI with java 8 it brokes, after few attempts, it seems that I was able to make it working back by downgrading error-prone back to 2.3.4 but only for java 8

not sure whether it is a good approach or not but at moment have no idea what to do next

**Comment by mac2000** [comment]
arghhhh, codecov is red 😂

should I add some tests for coverage to become +7%?

but then this PR won't be about upgrading error-prone

is there a way to bypass it?

**Comment by dzou** [comment]
> arghhhh, codecov is red 
> 
> should I add some tests for coverage to become +7%?
> 
> but then this PR won't be about upgrading error-prone
> 
> is there a way to bypass it?

Hey don't worry -- we can ignore the codecov for your PR since it's just upgrading the error prone version. I'll take a look.

**Comment by dzou** [comment]
Did some more digging, looks like someone else has same problem: https://github.com/codehaus-plexus/plexus-compiler/issues/77

However I'm not yet sure how they resolved their problem.

**Review by dzou — APPROVED** [review]
Based on my research here codehaus-plexus/plexus-compiler#77 I think downgrading the version might be the simplest solution. I couldn't figure out how to get `2.4.0` working for java 8.

@ttomsu @elefeint -- Let me know if you feel comfortable with the hard-coded version downgrade for java 8. If so then I can merge it in.

**Review by elefeint — APPROVED** [review]
I am fine with the manual override of the version, just add a comment on the line above to remind people why it's there.

**Review by meltsufin — APPROVED** [review]

**Comment by dzou** [comment]
> I am fine with the manual override of the version, just add a comment on the line above to remind people why it's there.

Done.

**Pull request merged**
