### PR TITLE
Firestore repo factory

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
Adds config boilerplate for Firestore repos

### CODE REVIEW

**Comment by ChengyuanZhao** [comment]
@dmitry-s There is that test in the autoconfig module I included that requests a bean of the arbitrary `FirestoreTestRepo` class I defined. So that one does verify user-defined repos can be generated.

As for actual CI of query method functionality i don't think that's possible at the moment since the PartTree class in this PR is just a placeholder :/

**Comment by dmitry-s** [comment]
@ChengyuanZhao The repository methods like count, findAll, save, etc. are already implemented in FirestoreReactiveRepository - can we test a couple of those?

**Comment by ChengyuanZhao** [comment]
@dmitry-s yes can do.

**Comment by ChengyuanZhao** [comment]
@dmitry-s PTAL added integration tests

**Comment by ChengyuanZhao** [comment]
@meltsufin @dmitry-s merged !

**Pull request merged**
