### PR TITLE
add != to PartTreeFirestoreQuery

### LINKED ISSUE #2563: Firestore: support '!=' and NOT_IN filter in name based queries
Firestore added '!=' filter, we can add support for it in name based queries.
Same for NOT_IN.

### PR DESCRIPTION
**Pull request by dmitry-s**
fixes #2563

### CODE REVIEW

**Review by meltsufin — CHANGES_REQUESTED** [review]
Looks good, but can you also update [this section](https://docs.spring.io/spring-cloud-gcp/docs/1.2.5.RELEASE/reference/html/#query-methods-by-convention-3) in the docs, please?

**Review by elefeint — APPROVED** [review]
+1 on docs updates.

**Comment by dzou** [comment]
Looks good. @meltsufin @dmitry-s -- Wanted to revisit our discussion of the new repo. Do you plan to include these changes in the new repo? I think we are getting a little out of sync with a few PRs related to datastore/firestore.

**Comment by dmitry-s** [comment]
adding support for NOT_IN as well

**Review by meltsufin — APPROVED** [review]

**Pull request merged**
