### PR TITLE
Fix Pub/Sub Tests

### PR DESCRIPTION
**Pull request by dzou**
Fixes pub/sub tests to repair the build.

### CODE REVIEW

**Comment by meltsufin** [comment]
The build still seems to be broken. I guess we have multiple issues with it.

**Comment by elefeint** [comment]
We are waiting until morning. Spring-cloud-build upgraded Spring Boot and then rolled back; it appears Travis has a maven cache.

**Comment by dzou** [comment]
Yup, it might be easiest to just merge #2256 in and then fix the build issues after.

**Comment by meltsufin** [comment]
> Yup, it might be easiest to just merge #2256 in and then fix the build issues after.

Sure, just merged.

**Comment by dzou** [comment]
Closing in favor of #2264.

**Pull request closed without merging**
