### PR TITLE
GH-1034: Align Pub/Sub Binder impl with SCSt core

### PR DESCRIPTION
**Pull request by artembilan**
Fixes spring-cloud/spring-cloud-gcp#1034

### CODE REVIEW

**Comment by meltsufin** [comment]
"Alight"? What does that mean?
Fixes #1034?
I was just starting the same fix last night. I will take a look soon.

**Comment by artembilan** [comment]
@meltsufin ,

Thank you for the pointers! 😃 

Fixed commit and PR description.

I somehow totally missed that issue.

Hope now it is good.

**Comment by artembilan** [comment]
Well, we really don't have those *extended* properties to test against.
And also there is no Docs changes on the matter there in Kafka Binder, neither in the Rabbit Binder: https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/commit/bf26977d7fe10be456e18c539421a94825dfbb65

Therefore I don't think that there left too much to do for this issue .

Thanks for consideration this change! Although would be great to have such a change in stream with fixes for all other binder.  😉 

/CC @sobychacko

**Comment by sobychacko** [comment]
@meltsufin That's correct.

**Comment by artembilan** [comment]
OK. What do you want from me to do here yet?
Is there any guidance how to proceed with your requirements?

I can extract a test-case on the matter from the mentioned PRs, but I definitely don't see there any docs changes. That's confusing... 🤷‍♂️ 

Thanks for understanding.

**Comment by artembilan** [comment]
>  I think docs are changed in the core docs

Right, that's why I insist do not change docs here. Or change docs for all involved binder implementations.

**Comment by meltsufin** [comment]
Where is this updated documentation? We should at least link to it then?

**Comment by sobychacko** [comment]
@meltsufin updated docs are here: https://docs.spring.io/spring-cloud-stream/docs/Fishtown.M3/reference/htmlsingle/#binding-properties
(just mentioned briefly there, how extended default properties could be configured).

**Pull request merged**
