### PR TITLE
Add configuration for Javadoc plugin

### PR DESCRIPTION
**Pull request by dzou**
Adds the initial configuration for javadoc plugin in this project; with intention to eventually figure out how to publish this thing.

### CODE REVIEW

**Comment by dzou** [comment]
> One thing to keep in mind is that we might not want to run it on regular builds because javadoc generation could add a significant amount of time to the build.

Hmm make sense, I think I will exclude it from the executions then. What is the best way to do this? For some reason the steps for building the javadocs is failing with compilation errors: https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/598689065?utm_source=github_status&utm_medium=notification

Feel like I am missing something with how the javadoc generation works.

**Comment by meltsufin** [comment]
> > One thing to keep in mind is that we might not want to run it on regular builds because javadoc generation could add a significant amount of time to the build.
> 
> Hmm make sense, I think I will exclude it from the executions then. What is the best way to do this? For some reason the steps for building the javadocs is failing with compilation errors: https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/598689065?utm_source=github_status&utm_medium=notification
> 
> Feel like I am missing something with how the javadoc generation works.

I think removing the automatic execution bound to `package` phase is fine.
Regarding compilation errors, are you sure it's caused by the javadoc stuff? It looks like the regular compilation is failing.

**Comment by dzou** [comment]
> > > One thing to keep in mind is that we might not want to run it on regular builds because javadoc generation could add a significant amount of time to the build.
> > 
> > 
> > Hmm make sense, I think I will exclude it from the executions then. What is the best way to do this? For some reason the steps for building the javadocs is failing with compilation errors: https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/598689065?utm_source=github_status&utm_medium=notification
> > Feel like I am missing something with how the javadoc generation works.
> 
> I think removing the automatic execution bound to `package` phase is fine.
> Regarding compilation errors, are you sure it's caused by the javadoc stuff? It looks like the regular compilation is failing.

Removed from automatic execution for now. I think the errors are related somehow; you see now, removing the automatic execution also resolves the compilation errors.

**Comment by meltsufin** [comment]
Maybe the command to Travis yaml to make sure it tests javadoc generation?

**Comment by dzou** [comment]
Resolved by #2173.

**Pull request closed without merging**
