### PR TITLE
 Avoid checks when spring-cloud-gcp-config is disabled

### LINKED ISSUE #245: Spring Cloud GCP Config - don't validate properties when disabled
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-config/src/main/java/org/springframework/cloud/gcp/config/GoogleConfigPropertySourceLocator.java

It's currently checking name/profile values to be set regardless of whether the starter has been disabled.  If disabled, it shouldn't force configure these values.

### PR DESCRIPTION
**Pull request by joaoandremartins**
Fixes #245

### CODE REVIEW

**Comment by artembilan** [comment]
??? What is this about?
Looks like a duplication of the #252

**Comment by joaoandremartins** [comment]
Indeed, but @saturnism went on vacations and the tests were failing on his PR, so we couldn't merge.

**Comment by artembilan** [comment]
Closed in favor of #260

**Comment by artembilan** [comment]
Oh! Sorry, I've mixed this one with the just merged fix for SCOPES. Shame on me 😢

**Comment by joaoandremartins** [comment]
@artembilan test added. PTAL

**Pull request merged**
