### PR TITLE
Spring Cloud GCP reference document initial commit

### PR DESCRIPTION
**Pull request by joaoandremartins**
This provides the reference document infrastructure, along with a very
rough document index.

### CODE REVIEW

**Comment by artembilan** [comment]
At a glance I can't review this, sorry.
I'm not familiar with docs infrastructure.
But I will follow what you've done so far.
Might be useful for me in other places.

**Comment by meltsufin** [comment]
@joaoandremartins What instructions or model did you follow for setting this up? I'm having a hard time validating it as well.

**Comment by joaoandremartins** [comment]
I looked at a few Spring project, but based on the most recent one I saw in [spring-boot](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-docs/src/main/asciidoc). They all have a gh-pages repo for the Github page and a "docs" folder in the master branch.

**Comment by meltsufin** [comment]
I thought that `gh-pages` branch with docs was all we needed. How will this PR publish the reference docs to the site?

**Comment by joaoandremartins** [comment]
Hmm that is a good question. The reference is generated on the `generate-resources` Maven phase. Although, with this config (e.g., backend = docbook5, similarly to spring-boot), XML is generated. I could generate HTML by changing the backend. I don't know how this will work in production, @artembilan do you know anyone on your side who knows about docs infrastructure who can help?

**Comment by artembilan** [comment]
I have added recently Docs into the newest my project: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/tree/master/spring-cloud-stream-binder-kinesis-docs. What I did was blind copy/paste from similar project for the Rabbit Binder.

In the end I like the result and after running `full` profile for `package` I have a zip with JavaDocs and all other possible Reference Manual views: epub, html, pdf.

There related commit is here: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/commit/26038f0c299651f860d50d59b8df7f65449d52f7

**Comment by joaoandremartins** [comment]
OK, I have copied the Maven profile from that project and the other necessary bits so that `mvn package -P full` would work. No Javadoc is generated for the docs module, so I had to delete the line that adds Javadoc to the zip.

@artembilan one more question, do you then manually copy a generated reference doc to the `gh-pages` repo so that it's linkable from the Github project page?

I've noticed a trend among Spring projects where all seem to use the [spring-cloud-static project](https://github.com/spring-cloud/spring-cloud-static/tree/gh-pages). Do we have to do anything so that whatever script updating the docs also picks up our project? cc @spencergibb who appears to be doing doc updates for Spring Cloud related projects.

**Comment by spencergibb** [comment]
@joaoandremartins spring-cloud-static is where individual and combined documentation for projects managed under the spring-cloud-dependencies BOM gets put. There might need to be changes to the docs to be included. @artembilan when is the planned release of spring-cloud-gcp?

**Comment by artembilan** [comment]
Sorry, I can't help with docs from here.
I just added that to my project with the hope that it will be somehow aggregated to the big Spring Cloud Stream doc alongside with other binders: http://docs.spring.io/spring-cloud-stream/docs/Elmhurst.BUILD-SNAPSHOT/reference/htmlsingle/#_binder_implementations.

I just didn't think about that yet. Too much to do still...

@spencergibb ,

Thank you for coming here with some feedback!

I don't know when the release is going to be. Should be some M1 already, but I think team decided to add docs, too.


Sorry that I'm so useless on the matter, but I really can't tell anything about managing docs... 😢

**Comment by joaoandremartins** [comment]
In that case, what I suggest is to merge this, keep working on it until we have a robust reference document and then add the project to the spring-cloud-dependencies BOM, which should take care of automatically publishing the reference doc to spring-cloud-static.

**Comment by spencergibb** [comment]
It doesn't automatically get added, but we could take the right steps at the right time.

**Comment by joaoandremartins** [comment]
@saturnism you mentioned earlier you might be able to help out with documentation. If you want to, you can edit the files at https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-docs/src/main/asciidoc to add content.

We can work out the kinks on publishing the reference doc to be linkable from our project page later.

**Comment by joaoandremartins** [comment]
@spencergibb do you know if any documentation on reference documentation exists? I took Artem's advice to copy the docs folder from another project, but now Github says 23% of the code in this project is XSLT which doesn't feel very nice.

Also, it feels like a catch-22 when in order to launch a Beta/GA of our project, we need to have a reference document but, in order to have the reference document, we need to add our project to the spring-cloud BOM, which assumes it is Beta/GA..

**Comment by spencergibb** [comment]
@joaoandremartins you can always publish docs to `gh-pages` in this repo. Being included in the spring-cloud BOM is only for consolidated documentation.

**Comment by meltsufin** [comment]
@spencergibb Is there a specific process that Spring projects follow for publishing docs to `gh-pages`?

**Comment by spencergibb** [comment]
https://github.com/spring-projects/gh-pages

**Comment by spencergibb** [comment]
Publishing the docs to gh-pages.

**Pull request merged**
