### PR TITLE
Re-ordered method parameters

### PR DESCRIPTION
**Pull request by dhoard**
Re-ordered method parameters to be more consistent with other methods within the class.

While this is not a functional change, it makes it more clean, clear, and consistent.

### CODE REVIEW

**Comment by meltsufin** [comment]
@dhoard Thank you for the contribution!
@artembilan I'm thinking that for now, we should make all changes that apply to both branches in `master`, and at some point before RC2 or GA we can do one PR to sync relevant deltas up to `1.0.x`.

**Comment by meltsufin** [comment]
@dhoard Would mind opening a similar PR against `master`? We can merge this one too.

**Comment by artembilan** [comment]
That makes sense, @meltsufin .

Let's open issue on the matter and gather there commits from `master` which should go into the `1.0.x` as back-porting task!

This way we indeed just will need to ask contributors to PR against `master`.

Thank you! Both

Let's push merge button then already!

**Comment by meltsufin** [comment]
Sounds good! https://github.com/spring-cloud/spring-cloud-gcp/issues/814

**Comment by dhoard** [comment]
@meltsufin PR against `master` created

**Comment by meltsufin** [comment]
Thanks! I guess we can just close this one and deal with the merge into `1.0.x` later along with other things.

**Comment by artembilan** [comment]
Does it matter, @meltsufin ?

We have this PR here already and it is really ready to be merged.
There is just need to push `Merge` button though...

I don't see reason to move this work to some other place... 
🤷‍♂️

**Comment by meltsufin** [comment]
I don't think it would add much additional work either way, but sure, I'll merge! :)

**Pull request merged**
