### PR TITLE
Enable Codecov reporting from Travis builds

### PR DESCRIPTION
**Pull request by meltsufin**

### CODE REVIEW

**Comment by meltsufin** [comment]
I think we need to add Jacoco as well.

**Comment by artembilan** [comment]
How to see the report here in PR from that Codecov?

And looks like Snyk is a noise and not so useful here on PR.
Plus it comes from my account 😢 ...

**Comment by meltsufin** [comment]
This PR is still WIP. (Partially) agreed about Snyk. We need to setup a bot account rather than yours. Let's discuss that separately.

**Comment by meltsufin** [comment]
@artembilan Ready for review now. I don't think the Codecov reports will kick in until we merge into master.

**Pull request merged**
