### PR TITLE
Release commit for 1.1.0.M2

### PR DESCRIPTION
**Pull request by spencergibb**

### CODE REVIEW

**Comment by spencergibb** [comment]
https://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-gcp-dependencies/1.1.0.M2/

/cc @artembilan @sobychacko

**Comment by artembilan** [comment]
Yeah... Looks like no: https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.M2/reference/htmlsingle/

Also we need to mentioned this Spring Cloud GCP project on the Spring Cloud page: https://projects.spring.io/spring-cloud/

**Comment by spencergibb** [comment]
Only the samples are skipped. The docs are not deployed. We'll need to work on that.

**Comment by spencergibb** [comment]
We also don't deploy docs to docs.spring.io

**Comment by meltsufin** [comment]
What's the release process now? We should updated https://github.com/spring-cloud/spring-cloud-gcp/blob/master/RELEASING.adoc.

**Comment by spencergibb** [comment]
It should all be automated. We'll need to sync up on a few things. We should schedule a short chat after spring one this week. I could go over the release tooling.

**Comment by meltsufin** [comment]
Sounds good. I will merge this for now!

**Comment by spencergibb** [comment]
Don't squash it

**Comment by spencergibb** [comment]
If it weren't a milestone, I'd be concerned, so I'm not worried. We'll work it out for the next time

**Comment by meltsufin** [comment]
Actually, the commits are only in your fork. So, tagging the commit won't work. Do you have admin rights on the repo, so you can temporarily enable rebase & merge?

**Comment by spencergibb** [comment]
I don't. Hence the PR.

**Comment by meltsufin** [comment]
@markfisher Should be able to help.

**Comment by meltsufin** [comment]
I will just split your 2 commits into 2 PRs.

**Comment by meltsufin** [comment]
Replaced by #1044

**Comment by meltsufin** [comment]
Tag created: https://github.com/spring-cloud/spring-cloud-gcp/releases/tag/v1.1.0.M2

**Comment by meltsufin** [comment]
Back to snapshots PR: #1045

**Pull request closed without merging**
