### PR TITLE
Fix property name for credentials file.

### PR DESCRIPTION
**Pull request by irvifa**
Property name should be:

```
spring.cloud.gcp.credentials.location
```

instead of:

```
spring.cloud.gcp.sql.credentials.location
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@irvifa Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2364)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2364) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@irvifa Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2364)!

**Comment by dmitry-s** [comment]
@irvifa just to clarify, what makes you think it should be `spring.cloud.gcp.credentials.location`?

**Comment by irvifa** [comment]
Hi @dmitry-s it's causing confusion since in the docs it's mentioned to use the `sql` one meanwhile the example using the general one, please refer to https://github.com/spring-cloud/spring-cloud-gcp/blob/4fdb7e325428d1779a60ae72104ec9c9f917ed31/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample/src/main/resources/application.properties#L16

**Pull request merged**
