### PR TITLE
Removes deprecated call

### PR DESCRIPTION
**Pull request by joaoandremartins**

### CODE REVIEW

**Comment by meltsufin** [comment]
Did I miss this one in my PR?

**Comment by joaoandremartins** [comment]
@meltsufin you might have configured your inspection to not run on tests perhaps?

**Comment by meltsufin** [comment]
I simply ran `mvn compile`. I dunno if that picks it up for tests.

**Comment by joaoandremartins** [comment]
I found [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206205679-Can-Intellij-code-analysis-find-all-instances-of-deprecated-code-in-a-project-directory-of-many-classes-) pretty neat!

**Pull request merged**
