### PR TITLE
Spanner onetomany annotation

### PR DESCRIPTION
**Pull request by ChengyuanZhao**
related to #853

This adds an annotation for marking child-collections and tests.

### CODE REVIEW

**Comment by nov1vinni** [comment]
So happy to see this implemented quicly. Hoping to see it released soon !!would reduce our effort drastically.

**Comment by ChengyuanZhao** [comment]
@meltsufin Renamed that isChildCollection() method, also fixed instances of Spanner -> Cloud Spanner.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao  Whats teh build version for this ? Is it avaibale in 1.1.0.BUILD-SNAPSHOT?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa yes, the snapshot is always what our repo looks like at the current moment. However this PR is just adding the annotation.

**Comment by ChengyuanZhao** [comment]
That work is still in progress. The checkboxes list in #853 keep track of where the progress is for the support for parent-child relationships.

**Pull request merged**
