### PR TITLE
Initial GitHub Actions workflow to test on multiple JDK versions

### PR DESCRIPTION
**Pull request by geertjanw**

### CODE REVIEW

**Comment by meltsufin** [comment]
@ttomsu Can you take a look, since you're familiar with GH actions?
I don't see any harm in this, but I think the Spring Team is already testing several JDK versions in their Jenkins CI.
cc/ @artembilan

**Comment by artembilan** [comment]
True. 
We really have those plans in the Spring GCP project pipeline: https://jenkins.spring.io/search/?q=gcp&Jenkins-Crumb=db7f22a2c893ab2e18235addf81bdff6586bcb80e990fca5f96670713e27c09a

Not sure though how is it going to be when we migrate project to your side.
So, probably using GH actions is the right direction to go.
(Not familiar though what is that)

**Comment by geertjanw** [comment]
> True.
> We really have those plans in the Spring GCP project pipeline: https://jenkins.spring.io/search/?q=gcp&Jenkins-Crumb=db7f22a2c893ab2e18235addf81bdff6586bcb80e990fca5f96670713e27c09a
> 
> Not sure though how is it going to be when we migrate project to your side.
> So, probably using GH actions is the right direction to go.
> (Not familiar though what is that)

GitHub has JDKs that are used automatically when you run GitHub Action workflows, such as for building and testing, which occur on the GitHub infrastructure. It's all well integrated, in the Actions tab of GitHub repos, via the configuration file in this PR.

**Comment by geertjanw** [comment]
Here you can see how it looks after the process is complete, on my fork of your repo, which happens automatically whenever a new merge is done in the repo:

https://github.com/geertjanw/spring-cloud-gcp/actions/runs/331803390

**Comment by meltsufin** [comment]
We are doing this with GH Actions in the new repo: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/f404bac2efd17bad3eef20a7317b7216c3eebb29/.github/workflows/buildAndTest.yaml#L24

**Comment by ttomsu** [comment]
As @meltsufin already mentioned, we're doing this in the new repo. This repo will become deprecated with the Ilford (2020.0.0) Spring Cloud Release, so if you have additional things you'd like to see/test out I'd love to see them in the new repo.

**Comment by meltsufin** [comment]
Just to be clear, this repo will remain for ongoing support of 1.x versions, including support for Spring Cloud Hoxton (Spring Cloud GCP v1.2.x).

**Review by ttomsu — APPROVED** [review]

**Pull request merged**
