### PR TITLE
nit: should delete subscription first

### PR DESCRIPTION
**Pull request by anguillanneuf**
It's good practice to delete the subscription(s) before deleting the topic(s) that they belong to.

### CODE REVIEW

**Comment by meltsufin** [comment]
@elefeint I wonder how the integration test even works since Pub/Sub won't allow you to delete a topic that has subscriptions.

**Comment by elefeint** [comment]
It does; I've even deleted topics and left orphan subscriptions through GCP console UI. Maybe behavior changed?

**Comment by meltsufin** [comment]
@elefeint Should we merge or close?

**Comment by elefeint** [comment]
Close, as order of REST endpoints does not matter. I'll address the integration test separately.

**Pull request closed without merging**
