### PR TITLE
Updated SecretManager from v1beta1 to v1

### PR DESCRIPTION
**Pull request by gwhitehawk**
SecretManager has been in GA since Q1 2020, it's about time to update the refs.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gwhitehawk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2638)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2638) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by dzou** [comment]
Hey thanks for the update, sorry we forgot about this. I will take a look.

**Review by dzou — APPROVED** [review]

**Comment by dzou** [comment]
Everything looks good @gwhitehawk , if you can just sign the Pivotal CLA I'll get this merged in.

**Comment by pivotal-issuemaster** [comment]
@gwhitehawk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-gcp&pullRequestId=2638)!

**Pull request merged**
