### PR TITLE
Added proxyBeanMethods = false to configuration classes for better GraalVM support

### LINKED ISSUE #2500: Switch spring-cloud-gcp autoconfigurations to proxyBeanMethods=false
Turning off bean method proxying is a best practice that helps performance and reduces graalvm compatibility issues.

Related to spring-projects/spring-boot#9068.

### LINKED ISSUE #2524: GraalVM Support
**Describe the bug**
I was playing around with getting a GraalVM native image up & running on Google Cloud Run.
During startup following error was thrown

```
org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration, org.springframework.cloud.gcp.logging.LoggingWebMvcConfigurer, org.springframework.cloud.gcp.autoconfigure.logging.StackdriverLoggingAutoConfiguration]
```

Checking other Spring Cloud Configuration classes I detected following issue: https://github.com/spring-cloud/spring-cloud-commons/issues/623 and corresponding commit: https://github.com/spring-cloud/spring-cloud-commons/commit/18a4227c4ef1bdf86c3103e64bce75847a53073e#diff-878bfcb22b53612b49e3b34e803d12d2

Would it make sense to move all
```
@ Configuration
```

to 
```
@Configuration(proxyBeanMethods = false)
```

If so, I'm happy to do this.

**Sample**
Google Cloud Run hello-world java sample with graalvm adaptions described here. I can create a sample repo if needed

https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.0/spring-graalvm-native-docs-0.8.0.zip!/reference/index.html#getting-started-buildpacks

### PR DESCRIPTION
**Pull request by gabac**
Fixed #2524 and fixes #2500

I didn't change samples and test configurations.

### CODE REVIEW

**Review by elefeint — CHANGES_REQUESTED** [review]
You'll have to make GcpCloudSqlAutoConfiguration and GcpStorageAutoConfiguration non-abstract for the tests to pass.
We've made them abstract to appease checkstyle, which no longer looks like a good tradeoff.

**Comment by gabac** [comment]
> You'll have to make GcpCloudSqlAutoConfiguration and GcpStorageAutoConfiguration non-abstract for the tests to pass.
> We've made them abstract to appease checkstyle, which no longer looks like a good tradeoff.

Thanks for the hint 👍 

According to the https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc I'm supposed to run

`$ bash util/update-license-year.sh`

this is failing for me with:
```

**Comment by dzou** [comment]
> > You'll have to make GcpCloudSqlAutoConfiguration and GcpStorageAutoConfiguration non-abstract for the tests to pass.
> > We've made them abstract to appease checkstyle, which no longer looks like a good tradeoff.
> 
> Thanks for the hint 
> 
> According to the https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc I'm supposed to run
> 
> `$ bash util/update-license-year.sh`
> 
> this is failing for me with:
> 
> ```
> Updating year to 2020 on files different from HEAD
> xargs: illegal option -- -
> ```

@gabac - No worries about it; we probably have to fix the instructions...

Thanks for your contribution, looks good!

**Review by dzou — APPROVED** [review]

**Review by meltsufin — APPROVED** [review]
Thanks for the contricution @gabac!
It's good to go in pending @elefeint's verification of the integration tests.

**Comment by gabac** [comment]
Happy to do this 👍

**Review by elefeint — APPROVED** [review]
After adding in the master build fixes, this PR passes with flying colors.

**Pull request merged**
