### PR TITLE
Making Logging a separate module outside of autoconfiguration

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes: #1448.

### CODE REVIEW

**Comment by meltsufin** [comment]
@artembilan I decided against the "stackdriver" module because there is nothing useful to put there for the trace stuff, only logging.

**Comment by meltsufin** [comment]
@artembilan I see your point. I did expect this to come up because there are some serious breaking changes, the most important of which is the path change to logback config files. I am, however, curious about the breaking changes policy. I have seen some breakage in minor versions of Spring like from Boot 2.0 to 2.1 and Framework 5.0 to 5.1, and even more so in Spring Cloud projects.
I'll try to make this a bit more backwards compatible. Perhaps we can import the logging configs from one file to the other.

**Comment by artembilan** [comment]
I'm not sure what you mean about Spring Framework, but we really had some breaking changes in Spring Boot from 2.0 to 2.1: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes
We had a big team discussion on the matter and those changes were really reasonable because previous behavior has just hidden an issue from us.

But that's fully different story and should be revised privately if that.

Anyway let's just don't make this breaking changes story like blaming each other! Let's try to keep our code from the breakage as much as possible. 
This way we will eliminate many questions and issues from community.

I think it won't hurt to keep content of those logging configs as identical. Doesn't look like we change it too often...

**Comment by meltsufin** [comment]
@artembilan I followed your suggestion to also keep the original classes and files as deprecated. Please take another look.

**Pull request merged**
